Feature: Enhance rebase commands to work on revision range

diff --git a/bin/range-seditor-bubble-down b/bin/range-seditor-bubble-down
--- a/bin/range-seditor-bubble-down
+++ b/bin/range-seditor-bubble-down
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # vim:tw=0:ts=2:sw=2:et:norl:ft=bash
-# Author: Landon Bouma (landonb &#x40; retrosoft &#x2E; com)
+# Author: Landon Bouma <https://tallybark.com/>
 # Project: https://github.com/depoxy/tig-newtons#🍎
 # License: MIT. Please find more in the LICENSE file.
 
@@ -9,9 +9,6 @@
 DX_SHOW_TODO=${DX_SHOW_TODO:-false}
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
-
-# SYNC_ME: The two bubble editors are similar:
-#   meld range-seditor-bubble-down range-seditor-bubble-up &
 
 # Git passes todo path, e.g., /proj/.git/rebase-merge/git-rebase-todo
 range_seditor_bubble_down () {
@@ -22,35 +19,85 @@ range_seditor_bubble_down () {
   # So do that now.
   echo
 
-  # Load `range_command_print_target_match`, `print_todo_maybe`.
+  # Load `range_command_print_start_match`, `print_todo_maybe`, etc.
   local tnewtons_bin="$(dirname "$0")"
   . "${tnewtons_bin}/range-command-common.sh"
 
   print_todo_maybe "${rebase_todo_path}" "before"
 
+  # Get the rebase command that our tig shell command stashed in
+  # the TNEWTONS_CRUMB_PATH=".git/tig-newtons-range-command" file.
   local rebase_cmd="$(range_command_print_command)"
-  local target_rev="$(range_command_print_target_object)"
-  local target_match="$(range_command_print_target_match)"
+  # Get the range tag commit grep strings (which may be same if
+  # only one commit selected -- i.e., the chosen_rev).
+  local start_match="$(range_command_print_start_match)"
+  local until_match="$(range_command_print_until_match)"
 
-  # DEV: This'd be your error.
-  [ -z "${rebase_cmd}" ] && >&2 echo "ERROR: What's command?" && exit 1 || true
+  # DEV: These'd be your error.
+  if false \
+    || [ -z "${rebase_cmd}" ] \
+    || [ -z "${start_match}" ] \
+    || [ "${start_match}" = "//" ] \
+    || [ -z "${until_match}" ] \
+    || [ "${until_match}" = "//" ] \
+  ; then
+    >&2 echo "ERROR: DEV: Missing one or more of:"
+    >&2 echo "- rebase_cmd: ${rebase_cmd}"
+    >&2 echo "- start_match: ${start_match}"
+    >&2 echo "- until_match: ${until_match}"
 
-  # If 'squash' or 'fixup', caller included previous commit that
-  # we need to 'squash' or 'fixup' into, in which case target_rev
-  # gets placed second, not first.
+    exit 1
+  fi
+
+  # If 'squash' or 'fixup', caller included previous commit that we
+  # need to 'squash' or 'fixup' into, in which case range_commits
+  # get placed second, not first.
   local is_first=1
   if [ "${rebase_cmd}" = "squash" ] || [ "${rebase_cmd}" = "fixup" ]; then
     is_first=0
   fi
 
-  # Use state to print target_rev commit first.
+  # Use arrays and state to print range_commits commits first.
   # - Also discard comment lines, who needs 'em.
+  # - Note using `print` from END sends output to terminal (stdout),
+  #   not to the inplace file; so use ENDFILE instead.
   awk -i inplace "
-    BEGIN { state = 0 }
-    state == 0 && ( ${is_first} || FNR == 2 ) { print \"${rebase_cmd} ${target_rev}\"; state = 1; }
-    \$0 ~ ${target_match} { next; }
+    BEGIN { state = 0; i_range = 0; i_other = 0; }
     \$0 ~ /^\$/ { next; }
     \$0 ~ /^#/ { next; }
+    state == 0 {
+      if (${is_first} || FNR >= 2) {
+        if (\$0 ~ ${start_match}) {
+          state = 1;
+        }
+        else {
+          other_commits[i_other] = \$2;
+          i_other++;
+          next;
+        }
+      }
+    }
+    state == 1 {
+      range_commits[i_range] = \$2;
+      i_range++;
+      if (\$0 ~ ${until_match}) {
+        state = 2;
+      }
+      next;
+    }
+    state == 2 {
+      other_commits[i_other] = \$2;
+      i_other++;
+      next;
+    }
+    ENDFILE {
+      for (i_todo = 0; i_todo < i_range; i_todo++) {
+        print \"${rebase_cmd} \" range_commits[i_todo];
+      }
+      for (i_todo = 0; i_todo < i_other; i_todo++) {
+        print \"pick \" other_commits[i_todo];
+      }
+    }
     1" ${rebase_todo_path}
 
   print_todo_maybe "${rebase_todo_path}" "after"
diff --git a/bin/range-seditor-bubble-up b/bin/range-seditor-bubble-up
--- a/bin/range-seditor-bubble-up
+++ b/bin/range-seditor-bubble-up
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # vim:tw=0:ts=2:sw=2:et:norl:ft=bash
-# Author: Landon Bouma (landonb &#x40; retrosoft &#x2E; com)
+# Author: Landon Bouma <https://tallybark.com/>
 # Project: https://github.com/depoxy/tig-newtons#🍎
 # License: MIT. Please find more in the LICENSE file.
 
@@ -12,8 +12,9 @@
 #
 # USETO:
 #
-#   Rebase so the first commit in the range (the ancestor commit)
-#   becomes the latest commit (the new HEAD), or is placed after
+#   Rebase so the first commit or range of commits become the latest
+#   commit(s) (where the last commit in the range is the new HEAD),
+#   or os that the first commit or range of commits is placed after
 #   another commit ahead of it (which is specified by a special
 #   Git tag).
 #
@@ -21,7 +22,7 @@
 #
 #   - The special tag feature only works when called via tig config
 #     shell command (specifically tig-newton's). If called otherwise,
-#     the editor will only move the bubble target to be latest commit.
+#     the editor will only move the oldest commit to be latest commit.
 #
 # REFER:
 #
@@ -34,9 +35,6 @@
 DX_SHOW_TODO=${DX_SHOW_TODO:-false}
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
-
-# SYNC_ME: The two bubble editors are similar:
-#   meld range-seditor-bubble-down range-seditor-bubble-up &
 
 # Git passes todo path, e.g., /proj/.git/rebase-merge/git-rebase-todo
 range_seditor_bubble_up () {
@@ -55,18 +53,45 @@ range_seditor_bubble_up () {
 
   local rebase_cmd="$(range_command_print_command)"
   local target_match="$(range_command_print_target_match)"
+  # The until_match is unset if only one commit being moved, else
+  # it represents the end of the selected commit range.
+  local until_match="$(range_command_print_until_match)"
 
   # DEV: This'd be your error.
-  [ -z "${rebase_cmd}" ] && >&2 echo "ERROR: What's command?" && exit 1 || true
+  if [ -z "${rebase_cmd}" ]; then
+    >&2 echo "ERROR: DEV: Missing rebase_cmd"
 
-  # Use state to print first commit after target rev.
+    exit 1
+  fi
+
+  # Use arrays and state to print first commit, or a range of commits,
+  # after target rev.
   # - Also discard comment lines, who needs 'em.
   awk -i inplace "
-    BEGIN { state = 0 }
-    state == 0 { first_commit = \$2; state = 1; next; }
-    state == 2 { print \"${rebase_cmd} \" first_commit; state = 3; }
-    \$0 ~ ${target_match} && state == 1 { state = 2; }
-    \$0 ~ /^\$/ && state == 1 { print \"${rebase_cmd} \" first_commit; state = 3; }
+    BEGIN { state = 0; i_range = 0; }
+    state == 0 {
+      range_commits[i_range] = \$2;
+      i_range++;
+      if ((\"${until_match}\" == \"//\") || (\$0 ~ ${until_match})) {
+        state = 1;
+      }
+      next;
+    }
+    state == 2 {
+      for (i_todo = 0; i_todo < i_range; i_todo++) {
+        print \"${rebase_cmd} \" range_commits[i_todo];
+      }
+      state = 3;
+    }
+    \$0 ~ ${target_match} && state == 1 {
+      state = 2;
+    }
+    \$0 ~ /^\$/ && state == 1 {
+      for (i_todo = 0; i_todo < i_range; i_todo++) {
+        print \"${rebase_cmd} \" range_commits[i_todo];
+      }
+      state = 3;
+    }
     \$0 ~ /^\$/ { next; }
     \$0 ~ /^#/ { next; }
     1" ${rebase_todo_path}
diff --git a/tig/config-diff b/tig/config-diff
--- a/tig/config-diff
+++ b/tig/config-diff
@@ -1,5 +1,5 @@
 # vim:tw=0:ts=2:sw=2:et:norl:ft=conf
-# Author: Landon Bouma (landonb &#x40; retrosoft &#x2E; com)
+# Author: Landon Bouma <https://tallybark.com/>
 # Project: https://github.com/depoxy/tig-newtons#🍎
 # License: MIT. Please find more in the LICENSE file.
 
@@ -12,44 +12,171 @@
 #
 # Only difference should be 'bind main...' vs. 'bind diff', so commands
 # don't apply to other views (pager, reflog, refs, stage, stash, status),
-# because tig config doesn't support reusing code for multiple commands
-# (alternating, we could immediately shell-out, but I'd rather not).
+# because tig config doesn't support reusing code for multiple commands.
+# - Note we try to shell-out as earlier as possible (to stay as DRY as
+#   possible), but there's still a bit of boilerplate, like verifying
+#   we can locate the shell script.
 #
-# In many case, using 'generic' is fine, if the binding doesn't shadow
-# other view bindings. But there are a few symbols defined only for the
-# special views, e.g., the ! binding is defined separately for multiple
-# views (reflogs, refs, stage, status).
-
-# YOU: Per DepoXy convention (htt
+# Not also that, in many cases, we prefer 'generic' to keep the config
+# simpler, which is fine if the binding doesn't shadow other view bindings.
+# But there are a few symbols defined only for the special views, e.g.,
+# the ! binding is defined separately for multiple views (reflogs, refs,
+# stage, status). It's those latter symbols that force us to use 'main'
+# and 'diff', so we don't clobber their use in other views.
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
 # SAVVY: If this returns nonzero, tig prints "Press Enter to continue".
-# - Otherwise we could prompt ourselves and return 0, but let's tig it.
+# - Otherwise we could wait-prompt ourselves and return 0, but let's tig it.
 bind diff ! >sh -c " \
   git_upraise_revision______________________ () { \
-    echo; \
     local tnewtons=\"${TIGNEWTONSPATH:-${TIGNEWTONSPATH:-${HOME}/.kit/git}/tig-newtons}\"; \
     if [ ! -d \"${tnewtons}\" ]; then \
-      >&2 echo \"ERROR: Please install tig-newtons to\"; \
+      >&2 echo; \
+      >&2 echo \"ERROR: To use this feature, please install tig-newtons to:\"; \
       >&2 echo \"  ${tnewtons}\"; \
       >&2 echo \"Or use the TIGNEWTONSPATH environ.\"; \
       >&2 echo; \
       return 1; \
     fi; \
-    local wipped=false; \
-    git add -A \
-      && git commit -q --no-verify -m 'PRIVATE: WIP [tig !]' \
-      && wipped=true; \
-    local bubble_cmd=\"${tnewtons}/bin/git-rebase-bubble-commit\"; \
-    echo \"git rebase -i %(commit)^\"; \
-    local exit_val; \
-    ${bubble_cmd} \"%(commit)^\" ${wipped}; \
-    exit_val=$?; \
-    ${wipped} && git reset --mixed @~1; \
-    echo; \
-    return ${exit_val}; \
+    \
+    local range_cmd=\"${tnewtons}/bin/range-command-apply-rebase\"; \
+    ${range_cmd} \"latest\" \"%(branch)\" \"%(commit)\"; \
   }; git_upraise_revision______________________"
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+# The following commands work on a range on commits.
+#
+# - The mechanism works across two or three commands:
+#
+#   - The user first selects and marks a commit with a special tag.
+#     - This will either be one end of a range, or it'll be a single
+#       commit the user wants to act upon.
+#   - The user may then optionally select another commit to mark the
+#     other end of the range, if they want to act on a range of commits
+#     as opposed to just one.
+#   - Finally, the use selects a target commit and chooses an action:
+#     - Cherry-pick first rev. or range to latest;
+#     - Move first rev. or range before or after target rev.; or
+#     - Squash or Fixup first rev. or range into target rev.
+#   - Note that user cannot move, squash, or fixup commits if viewing
+#     a branch other than the current branch (and similarly, while you
+#     can cherry-pick from the current branch, the more popular use case
+#     is cherry-picking from a different branch into the current branch).
+#   - Note we could instead create multiple bindings, one for each
+#     action, but that's at least 5 commands, and we don't have many
+#     available keyboard bindings remaining from which to pick. So when
+#     the user selects the target commit, we'll prompt them for the action.
+#
+# - Note using `+sh` vs. `>sh`:
+#   - The 'main' view updates immediately on `bind main [ >sh ...`,
+#     but it doesn't update on `bind main [ +sh ...`. But it's
+#     the latter that lets us echo to the status line. Phooey.
+#   - I tested each refresh-mode, including periodic, and only
+#     `refresh-mode = after-command` with `>sh` causes refresh.
+#   - It'd be nice to print a status message, e.g.,
+#       echo \"Now select a later commit and press ']'...\";
+#     but, oh well, nothing we can't solve in post!:
+#     - MAYBE/2023-02-13: Another tig PR idea: Refresh view on '+sh';
+#       or maybe it's that 'periodic' or 'auto' only check if commit
+#       history changed, but don't monitor tags.
+#       - For now, prefer >sh over +sh so 'main' refreshes and shows
+#         tag changes.
+
+# ***
+
+# Note: Cannot print URL with anchor link:
+#   https://github.com/DepoXy/tig-newtons#setup
+# Because tig replies "No output" when you try to run the function
+# (an educated guesser might assume tig doesn't allow comment
+#  characters in inline shell code).
+# - I tried `echo -e` but tig echoes the '-e', oddly, e.g.,
+#     echo -e \"https://github.com/DepoXy/tig-newtons\\x23setup\";
+#   Prints to status:
+#     -e https://github.com/DepoXy/tig-newtons\x23setup
+# - Nor does `printf \"\\x23\"` work (prints '\x23').
+# - However, Bash'ing out works fine (`/bin/bash -c ...`).
+
+bind diff [ >sh -c " \
+  revision_range_cmd__select_first_commit___ () { \
+    local tnewtons=\"${TIGNEWTONSPATH:-${TIGNEWTONSPATH:-${HOME}/.kit/git}/tig-newtons}\"; \
+    if [ ! -d \"${tnewtons}\" ]; then \
+      local readme_url=\"https://github.com/DepoXy/tig-newtons\\x23setup\"; \
+      /bin/bash -c \"echo -e 'ERROR: Setup tig-newtons properly to use this feature — ${readme_url}'\"; \
+      return 1; \
+    fi; \
+    \
+    local range_cmd=\"${tnewtons}/bin/range-command-apply-rebase\"; \
+    ${range_cmd} \"mark_first\" \"%(branch)\" \"%(commit)\"; \
+  }; revision_range_cmd__select_first_commit___"
+
+bind diff ] >sh -c " \
+  revision_range_cmd__select_final_commit___ () { \
+    local tnewtons=\"${TIGNEWTONSPATH:-${TIGNEWTONSPATH:-${HOME}/.kit/git}/tig-newtons}\"; \
+    if [ ! -d \"${tnewtons}\" ]; then \
+      local readme_url=\"https://github.com/DepoXy/tig-newtons\\x23setup\"; \
+      /bin/bash -c \"echo -e 'ERROR: Setup tig-newtons properly to use this feature — ${readme_url}'\"; \
+      return 1; \
+    fi; \
+    \
+    local range_cmd=\"${tnewtons}/bin/range-command-apply-rebase\"; \
+    ${range_cmd} \"mark_final\" \"%(branch)\" \"%(commit)\"; \
+  }; revision_range_cmd__select_final_commit___"
+
+# ***
+
+# MAYBE: Should '{' clear start_tag(s), and '}' clear until_tag(s)?
+#        Or should just '{' (and/or '}') clear all tags?
+#        - For now, '{' clears all tags, but this might change.
+
+# SYNC_ME: See same-named function in range-command-apply-rebase.
+bind diff { >sh -c " \
+  tags_delete_range_tags____________________ () { \
+    git tag | grep \"^[🚩🏁]-.\\+-🍏$\" | xargs -n 1 -I % git tag -d % > /dev/null; \
+  }; tags_delete_range_tags____________________"
+
+# ***
+
+# Notes on %(prompt) usage:
+# - While %(prompt) is nice because you can interact with user within tig,
+#   it has some limitations:
+#   - The %(prompt) resolves before the shell code runs, so there's a chance
+#     user didn't set start_tag or until_tag, and we'll prompt and then fail.
+#   - If we shelled-out to prompt, we could `read -n 1` and save user an Enter.
+# - We'll try %(prompt) for now and see how it goes.
+#   - For successful rebases, tig will momentarily shell-out to show rebase
+#     output, but no further interaction will be necessary, so user will be
+#     quickly returned to tig. This seems like smoother UX than shelling-out
+#     to prompt user, then returning to tig.
+
+# Note we use >sh and not +sh because user will need to review git-rebase
+# output if there's a conflict.
+
+bind diff \ >sh -c " \
+  revision_range_cmd__apply_range_action____ () { \
+    local action=\"%(prompt Choose action: [p]ick, [b]efore, [a]fter, [s]quash, or [f]ixup ? )\"; \
+    local tnewtons=\"${TIGNEWTONSPATH:-${TIGNEWTONSPATH:-${HOME}/.kit/git}/tig-newtons}\"; \
+    if [ ! -d \"${tnewtons}\" ]; then \
+      local readme_url=\"https://github.com/DepoXy/tig-newtons\\x23setup\"; \
+      >&2 echo \"ERROR: To use this feature, please install tig-newtons to:\"; \
+      >&2 echo \"  ${tnewtons}\"; \
+      >&2 echo \"Or use the TIGNEWTONSPATH environ.\"; \
+      >&2 echo; \
+      /bin/bash -c \">&2 echo -e '- Hint: Read the README — ${readme_url}'\"; \
+      >&2 echo; \
+      return 1; \
+    fi; \
+    \
+    local range_cmd=\"${tnewtons}/bin/range-command-apply-rebase\"; \
+    ${range_cmd} \"${action}\" \"%(branch)\" \"%(commit)\"; \
+  }; revision_range_cmd__apply_range_action____"
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+# FIXME/2023-02-13 16:46: Add 'undo-rebase' command.
+# - Can I use reflog and find previous HEAD?
+# - Or you could record HEAD (after WIPing) to .git/.tignewtons-foo
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
