Update: UX: Print warning if range commands not run via Bash

diff --git a/bin/range-command-apply-rebase b/bin/range-command-apply-rebase
--- a/bin/range-command-apply-rebase
+++ b/bin/range-command-apply-rebase
@@ -741,17 +741,19 @@ do_action_latest () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+PROG_NAME="range-command-apply-rebase"
+
 main () {
   source_deps
 
   range_command_muxxer "$@"
 }
 
+# Complain if sourced (from any shell), or not run via Bash.
 if [ -z "${BASH_SOURCE}" ] || [ "$0" != "${BASH_SOURCE[0]}" ]; then
-  # Though really `tig` runs this script with /bin/sh, so be POSIX.
-  >&2 echo "ERROR: Run this script with bash"
+  >&2 echo "ERROR: Run this script with Bash [${PROG_NAME}]"
 
-  exit 1
+  false
 else
   main "$@"
 fi
diff --git a/bin/range-seditor-bubble-down b/bin/range-seditor-bubble-down
--- a/bin/range-seditor-bubble-down
+++ b/bin/range-seditor-bubble-down
@@ -105,11 +105,18 @@ range_seditor_bubble_down () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+PROG_NAME="range-seditor-bubble-down"
+
 main () {
   range_seditor_bubble_down "$@"
 }
 
-if [ "$0" = "${BASH_SOURCE[0]}" ]; then
+# Complain if sourced (from any shell), or not run via Bash.
+if [ -z "${BASH_SOURCE}" ] || [ "$0" != "${BASH_SOURCE[0]}" ]; then
+  >&2 echo "ERROR: Run this script with Bash [${PROG_NAME}]"
+
+  false
+else
   main "$@"
 fi
 
diff --git a/bin/range-seditor-bubble-up b/bin/range-seditor-bubble-up
--- a/bin/range-seditor-bubble-up
+++ b/bin/range-seditor-bubble-up
@@ -110,11 +110,18 @@ range_seditor_bubble_up () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+PROG_NAME="range-seditor-bubble-up"
+
 main () {
   range_seditor_bubble_up "$@"
 }
 
-if [ "$0" = "${BASH_SOURCE[0]}" ]; then
+# Complain if sourced (from any shell), or not run via Bash.
+if [ -z "${BASH_SOURCE}" ] || [ "$0" != "${BASH_SOURCE[0]}" ]; then
+  >&2 echo "ERROR: Run this script with Bash [${PROG_NAME}]"
+
+  false
+else
   main "$@"
 fi
 
