Improve: Add missing staging-check and WIP-wrapper to Drop Commit (<C-o>)
- The Drop Commit (<C-o>) command would fail when run and there was
  staged or untracked changes.

- This commit adds the same boilerplate that the other commands use,
  to not run if staged work, and to temporary WIP-commit untracked
  work.

  - This is the last and final command to get this update.

    - Funny how the stuff that takes 10 minutes to fix is also
      the stuff you take 10 months to fix...

diff --git a/tig/bind-rebase b/tig/bind-rebase
--- a/tig/bind-rebase
+++ b/tig/bind-rebase
@@ -258,6 +258,15 @@ bind generic + >sh -c " \
 # - So mapping <C-o> to drop commit (mnemonic: drOp).
 bind generic <C-o> >sh -c " \
   git_drop_revision_________________________ () { \
+    ! git diff --cached --quiet \
+      && printf '%s\\n\\n' 'ERROR: <C-o> disabled while staging' \
+      && return 1 || true; \
+    \
+    local wipped=false; \
+    git add -A \
+      && git commit -q --no-verify -m \"${PRIVATE_PREFIX:-PRIVATE: }WIP [tig <C-o>]\" > /dev/null \
+      && wipped=true; \
+    \
     printf \"Really drop %(commit)? [Y/n] \"; \
     read input; \
     if [ -z \"${input}\" ] || [ \"${input}\" = \"Y\" ] || [ \"${input}\" = \"y\" ]; then \
@@ -288,10 +297,14 @@ bind generic <C-o> >sh -c " \
         [ -n \"${GIT_POST_REBASE_EXEC}\" ] \
           && eval ${GIT_POST_REBASE_EXEC}; \
         \
+        ${wipped} && git reset -q --mixed @~1; \
+        \
         echo; \
       fi; \
     else \
       echo \"Ope\"; \
+      \
+      ${wipped} && git reset -q --mixed @~1; \
       \
       echo; \
     fi; \
