Feature: Add post-rebase GIT_REBASE_TODO_PATH call to drop-commit (<C-o>)

diff --git a/tig/bind-rebase b/tig/bind-rebase
--- a/tig/bind-rebase
+++ b/tig/bind-rebase
@@ -234,16 +234,36 @@ bind generic <C-o> >sh -c " \
     read input; \
     if [ -z \"${input}\" ] || [ \"${input}\" = \"Y\" ] || [ \"${input}\" = \"y\" ]; then \
       echo \"git rebase --onto %(commit)^ %(commit)\"; \
-      if ! git rebase --onto %(commit)^ %(commit) || [ -f \".git/rebase-merge/git-rebase-todo\" ]; then \
+      \
+      local retcode=0; \
+      git rebase --onto %(commit)^ %(commit); \
+      retcode=$?; \
+      \
+      GIT_REBASE_TODO_PATH=\".git/rebase-merge/git-rebase-todo\"; \
+      if [ ${retcode} -ne 0 ] || [ -f \"${GIT_REBASE_TODO_PATH}\" ]; then \
+        if [ -n \"${GIT_POST_REBASE_EXEC}\" ]; then \
+          GITSMART_POST_REBASE_EXECS_TAG=\" $(echo '16i 23 P' | dc)git-abort\"; \
+          echo \"exec ${GIT_POST_REBASE_EXEC}\" \
+            \"${GITSMART_POST_REBASE_EXECS_TAG}\" \
+              >> \"${GIT_REBASE_TODO_PATH}\"; \
+        fi; \
+        \
+        local also_why=''; \
+        [ ${retcode} -ne 0 ] || also_why='\n (says .git/rebase-merge/git-rebase-todo)'; \
+        \
         >&2 echo; \
-        >&2 echo \"Killing \\`tig\\` because you got work to do\"; \
+        >&2 echo \"Killing \\`tig\\` because you got work to do${also_why}\"; \
         >&2 echo \"  🥩 🥩 chop chop\"; \
         \
         kill -s 9 $PPID; \
+      else \
+        [ -n \"${GIT_POST_REBASE_EXEC}\" ] \
+          && eval ${GIT_POST_REBASE_EXEC}; \
       fi; \
     else \
       echo \"Ope\"; \
     fi; \
+    \
     echo; \
   }; git_drop_revision_________________________"
 
